# Generated by Django 5.2.12 on 2026-03-29 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('score_total', models.FloatField(default=0.0)),
                ('score_grade', models.CharField(default='A', max_length=2)),
                ('pattern_count', models.IntegerField(default=0)),
                ('unique_categories', models.IntegerField(default=0)),
                ('corroborated_count', models.IntegerField(default=0)),
                ('audit_report', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['url', '-scanned_at'], name='scans_audit_url_07892f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('element_selector', models.TextField()),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('corroborated', models.BooleanField(default=False)),
                ('analyzer_name', models.CharField(max_length=64)),
                ('platform_context', models.CharField(default='general', max_length=64)),
                ('regulation_refs', models.JSONField(default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='scans.auditscan')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
